name: 'OSV Security Scan - Scheduled'

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: read
  issues: write

jobs:
  weekly-scan:
    name: 'Weekly Security Scan'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Full OSV Scanner
        id: osv-scan
        uses: radioactivetobi/roguepkg@v1  # Or use ./ for local testing
        with:
          scan-path: '.'
          malware-only: 'false' # Full scan including all vulnerabilities
          fail-on-malware: 'true'
          fail-on-vulnerability: 'false' # Don't fail on regular CVEs
        continue-on-error: true
      
      - name: Create Issue if Malware Found
        if: steps.osv-scan.outputs.malware-found > 0
        uses: actions/github-script@v7
        with:
          script: |
            const malwareCount = '${{ steps.osv-scan.outputs.malware-found }}';
            const vulnCount = '${{ steps.osv-scan.outputs.vulnerabilities-found }}';
            const totalScanned = '${{ steps.osv-scan.outputs.total-scanned }}';
            
            const issueBody = `## 🚨 Weekly Security Scan Alert
            
            **Malware has been detected in the project dependencies!**
            
            ### Scan Results
            - 🦠 Malware packages: **${malwareCount}**
            - ⚠️  Vulnerable packages: ${vulnCount}
            - 📦 Total packages scanned: ${totalScanned}
            
            ### Action Required
            1. Review the workflow logs for detailed information
            2. Identify and remove malicious packages
            3. Update to safe versions
            4. Re-run security scan
            
            ### Links
            - [View Workflow Run](${context.payload.repository.html_url}/actions/runs/${context.runId})
            - [OSV.dev Database](https://osv.dev)
            
            ---
            <sub>This issue was automatically created by the weekly security scan.</sub>`;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🚨 Security Alert: Malware Detected in Dependencies`,
              body: issueBody,
              labels: ['security', 'malware', 'dependencies']
            });

